# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ee/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo `pwd`
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - cp 'basic-example.adoc' /opt/build-space/
    - java -jar /opt/build-space/Example_AsciiDoctorJ.jar
    - rm /opt/build-space/basic-example.adoc

  artifacts:
    paths:
      - "/opt/build-space/*.pdf"

test2:
  stage: test
  script:
    - rm /opt/build-space/*.pdf
    - echo "Cleaned up build-space!"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
