build1:
  stage: build
  script:
    - cp 'basic-example.adoc' /opt/build-space/
    - pushd /opt/build-space/ && java -jar /opt/build-space/Example_AsciiDoctorJ.jar
    - rm -f /opt/build-space/basic-example.adoc
    - popd
    - mv /opt/build-space/*.pdf .

  artifacts:
    paths:
      - "*.pdf"

test1:
  stage: test
  script:
    - rm -f /opt/build-space/*.pdf
    - echo "Cleaned up build-space!"

deploy1:
  stage: deploy
  script:
    - echo "Done!"
